BlogBundle\Entity\Tag:
    type: entity
    table: tags
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false

    oneToMany:
        entryTag:
           targetEntity: EntryTag
           mappedBy: tag
           cascade: ["persist"]
    lifecycleCallbacks: {  }
