BlogBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        surname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        image:
            type: blob
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
